const courses={riverside:{name:'Riverside Country Club',pars:[4,5,3,4,4,3,5,4,4,4,3,5,4,4,3,4,5,4],si:[11,3,15,7,1,17,5,13,9,10,18,4,8,14,16,2,6,12],yards:[412,531,166,389,404,183,548,362,421,405,175,520,434,378,154,447,536,409]},meadow:{name:'Meadow Links',pars:[4,4,3,5,4,4,3,5,4,4,3,4,5,4,3,4,5,4],si:[7,13,17,3,1,11,15,5,9,10,18,2,6,16,14,4,8,12],yards:[396,372,158,524,428,391,176,541,404,398,162,410,534,389,148,438,519,403]}};
const savedCourse=JSON.parse(localStorage.getItem('fairwayCustomCourse'));if(savedCourse)courses.imported=savedCourse;
let importedSI=(savedCourse?.si||courses.riverside.si).slice();function renderImport(){ $('importCourseName').value=savedCourse?.name||'New Course';$('siGrid').innerHTML=importedSI.map((n,i)=>`<label class="si-cell"><span>HOLE ${i+1}</span><input data-si="${i}" type="number" min="1" max="18" value="${n}"></label>`).join('');document.querySelectorAll('[data-si]').forEach(x=>x.onchange=e=>{const i=+e.target.dataset.si,v=+e.target.value;if(v>=1&&v<=18)importedSI[i]=v;else e.target.value=importedSI[i]})}function previewPhoto(file){if(!file)return;const r=new FileReader();r.onload=()=>{$('photoPreview').innerHTML=`<img src="${r.result}" alt="Selected course scorecard">`;toast('Scorecard photo added — check the indices below')};r.readAsDataURL(file)}
let state=JSON.parse(localStorage.getItem('fairwayTournament'))||{name:'Riverside Summer Cup',course:'riverside',date:'2026-08-09',players:[{name:'Alex Morgan',handicap:12},{name:'Jamie Lee',handicap:18},{name:'Sam Patel',handicap:8},{name:'Taylor Reid',handicap:24}],hole:0,scores:{}};
let scorecardFile=null;function loadOcr(){if(window.Tesseract)return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('OCR library could not be loaded'));document.head.appendChild(s)})}function findSI(text){const labels=[...text.matchAll(/\bS\.?\s*I\.?\b/gi)];for(const label of labels){const values=(text.slice(label.index,label.index+220).match(/\b(?:[1-9]|1[0-8])\b/g)||[]).map(Number);for(let i=0;i<=values.length-18;i++){const row=values.slice(i,i+18);if(new Set(row).size===18&&Math.min(...row)===1&&Math.max(...row)===18)return row}}return null}async function runOcr(){if(!scorecardFile)return;const button=$('runOcr'),status=$('ocrStatus');button.disabled=true;status.textContent='Loading OCR and reading the S.I. row…';let worker;try{await loadOcr();worker=await Tesseract.createWorker('eng');const result=await worker.recognize(scorecardFile);const indices=findSI(result.data.text);if(!indices)throw new Error('No complete S.I. or SI row was found');importedSI=indices;renderImport();status.textContent='S.I. row found and imported. Please check every number.';toast('Stroke indices imported')}catch(error){status.textContent=`Couldn’t read an S.I. row. Please enter the values manually.`;toast('OCR needs a clearer scorecard photo')}finally{if(worker)await worker.terminate();button.disabled=false}}
const $=x=>document.getElementById(x),course=()=>courses[state.course];
document.title='Birdie Board';const brandFont=document.createElement('link');brandFont.rel='stylesheet';brandFont.href='https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,600;1,700&display=swap';document.head.appendChild(brandFont);const homeBrand=document.querySelector('#home header');homeBrand.querySelector('.eyebrow').textContent='BIRDIE BOARD';homeBrand.querySelector('h1').innerHTML='Birdie<br><i>Board.</i>';homeBrand.querySelector('h1').style.cssText="font-family:'Cormorant Garamond',serif;font-style:italic;font-weight:700;font-size:43px;line-height:.78;letter-spacing:-2px";
setTimeout(()=>{const secureApp=document.createElement('script');secureApp.src='./supabase-ui.js?v=20260817-3';document.head.appendChild(secureApp)},0);
$('openImport').onclick=()=>{renderImport();go('import')};function chooseScorecard(file){scorecardFile=file;previewPhoto(file);$('runOcr').disabled=!file;$('ocrStatus').textContent=file?'Ready to find the S.I. row.':'OCR runs in your browser. Always check the imported numbers.'}$('photoPicker').onchange=e=>chooseScorecard(e.target.files[0]);$('cameraPicker').onchange=e=>chooseScorecard(e.target.files[0]);$('runOcr').onclick=runOcr;$('applyImport').onclick=()=>{const name=$('importCourseName').value.trim()||'Imported Course',numbers=[...new Set(importedSI)];if(numbers.length!==18||Math.min(...numbers)!==1||Math.max(...numbers)!==18){toast('Use every stroke index from 1 to 18 once');return}courses.imported={name,si:importedSI.slice(),pars:courses.riverside.pars.slice(),yards:courses.riverside.yards.slice()};localStorage.setItem('fairwayCustomCourse',JSON.stringify(courses.imported));if(!$('courseSelect').querySelector('[value="imported"]'))$('courseSelect').insertAdjacentHTML('beforeend',`<option value="imported">${name}</option>`);$('courseSelect').value='imported';state.course='imported';save();go('setup');toast('Imported course is ready')};
function save(){localStorage.setItem('fairwayTournament',JSON.stringify(state));render()}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.go===id));render();window.scrollTo(0,0)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1700)}
function strokes(hcp,hole){return Math.floor(hcp/18)+(course().si[hole]<=hcp%18?1:0)}
function points(gross,hcp,hole){if(gross==null)return 0;const net=gross-strokes(hcp,hole),d=course().pars[hole]-net;return Math.max(0,d+2)}
function playerScores(i){return state.scores[i]||Array(18).fill(null)}function total(i){return playerScores(i).reduce((x,v,h)=>x+points(v,state.players[i].handicap,h),0)}function played(i){return playerScores(i).filter(x=>x!==null).length}
function renderHome(){const c=course();$('homeTournament').textContent=state.name;$('homeCourse').textContent=`${c.name} · ${new Date(state.date+'T12:00').toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})}`;$('tournamentCard').innerHTML=`<div class="card-title"><h3>${state.name}</h3><span class="badge">STABLEFORD</span></div><p class="course">${c.name} · ${state.players.length} competitors</p><div class="stats"><div><span>COURSE PAR</span><b>${c.pars.reduce((a,b)=>a+b)}</b></div><div><span>HOLES PLAYED</span><b>${Math.max(...state.players.map((_,i)=>played(i)))}/18</b></div><div><span>LEADER</span><b>${leader()?.name.split(' ')[0]||'—'}</b></div></div>`;$('recent').innerHTML='<div><span>Spring Invitational · Stableford</span><b>42 pts</b></div><div><span>Club Medal · Net strokeplay</span><b>71</b></div>'}
function leader(){return [...state.players].sort((a,b)=>total(state.players.indexOf(b))-total(state.players.indexOf(a)))[0]}
function renderPlayers(){ $('playerList').innerHTML=state.players.map((p,i)=>`<div class="player"><label>Name<input data-name="${i}" value="${p.name}"></label><label class="handicap">Handicap<input data-hcp="${i}" type="number" min="0" max="54" value="${p.handicap}"></label><button class="remove" data-remove="${i}">×</button></div>`).join('');document.querySelectorAll('[data-name]').forEach(x=>x.onchange=e=>{state.players[e.target.dataset.name].name=e.target.value;save()});document.querySelectorAll('[data-hcp]').forEach(x=>x.onchange=e=>{state.players[e.target.dataset.hcp].handicap=Math.max(0,Math.min(54,+e.target.value||0));save()});document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=e=>{state.players.splice(e.target.dataset.remove,1);save()})}
function renderScoring(){const c=course(),h=state.hole;$('scoringName').textContent=state.name;$('scoringCourse').textContent=c.name.toUpperCase();$('holeLabel').textContent=`Hole ${h+1} · Par ${c.pars[h]}`;$('holeNo').textContent=h+1;$('par').textContent=c.pars[h];$('si').textContent=c.si[h];$('yards').textContent=c.yards[h];const lead=leader();$('leader').textContent=`${lead?lead.name.split(' ')[0]+' · '+total(state.players.indexOf(lead))+' pts':'—'}`;$('holePills').innerHTML=c.pars.map((_,i)=>`<button class="${i===h?'active':''} ${state.players.some((_,p)=>playerScores(p)[i]!==null)?'done':''}" data-hole="${i}">${i+1}</button>`).join('');document.querySelectorAll('[data-hole]').forEach(x=>x.onclick=e=>{state.hole=+e.target.dataset.hole;save()});$('strokeTip').textContent=`Stroke index ${c.si[h]} — a player with handicap ${c.si[h]} or higher receives a stroke here.`;$('scorerRows').innerHTML=state.players.map((p,i)=>{let v=playerScores(i)[h]??c.pars[h];return `<div class="scorer"><div><strong>${p.name}</strong><small>HCP ${p.handicap} · ${strokes(p.handicap,h)} stroke${strokes(p.handicap,h)===1?'':'s'}</small></div><div class="score-step"><button data-change="${i},-1">−</button><b>${v}</b><button data-change="${i},1">+</button></div><div class="points">${points(v,p.handicap,h)}</div></div>`}).join('');document.querySelectorAll('[data-change]').forEach(x=>x.onclick=e=>{let [i,d]=e.target.dataset.change.split(',').map(Number),a=playerScores(i);a[h]=Math.max(1,Math.min(12,(a[h]??c.pars[h])+d));state.scores[i]=a;save()});$('leaderRows').innerHTML=[...state.players].map((p,i)=>({p,i,pts:total(i)})).sort((a,b)=>b.pts-a.pts).map((x,i)=>`<div class="leader"><span class="${i===0?'first':''}">${i+1}</span><b>${x.p.name}</b><strong>${x.pts} pts</strong><span>${played(x.i)} thru</span></div>`).join('')}
function render(){renderHome();renderPlayers();renderScoring()}
Object.entries(courses).forEach(([id,c])=>$('courseSelect').insertAdjacentHTML('beforeend',`<option value="${id}">${c.name}</option>`));$('courseSelect').value=state.course;$('tDate').value=state.date;
$('tournamentForm').onsubmit=e=>{e.preventDefault();state.name=$('tName').value.trim()||'Untitled Tournament';state.course=$('courseSelect').value;state.date=$('tDate').value;save();go('players')};$('newTournament').onclick=()=>go('setup');$('navSetup').onclick=()=>go('setup');$('enterScoring').onclick=()=>go('scoring');document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));$('addPlayer').onclick=()=>{state.players.push({name:'New competitor',handicap:18});save()};$('saveTournament').onclick=()=>{save();go('scoring');toast('Tournament is ready to score')};$('nextHole').onclick=()=>{if(state.hole<17){state.hole++;save();toast(`Scoring hole ${state.hole+1}`)}else toast('Final hole — finish when ready')};$('finish').onclick=()=>{if(confirm('Save the tournament result?')){toast('Tournament result saved');go('home')}};render();
